type: Generator
stop_generator_when_sequence_finishes: ALL
max_runtime_ms: 1500000
seed: 1
generator_schema: |
  SEQUENCE UINT64 0 40000000 1
  SEQUENCE FLOAT32 4.0 8.0 0.1
  SEQUENCE FLOAT32 2.0 4.0 0.1
  SEQUENCE FLOAT32 1.0 6.0 0.1
  SEQUENCE FLOAT32 0.1 3.0 0.1
  SEQUENCE FLOAT32 4.0 8.0 0.1
  SEQUENCE FLOAT32 2.0 4.0 0.1
  SEQUENCE FLOAT32 1.0 6.0 0.1
  SEQUENCE FLOAT32 0.1 3.0 0.1
